spring.application.name=Medshare
spring.data.mongodb.uri=mongodb+srv://amanna:amanna1041@medicineshareapp-cluste.4bqm9.mongodb.net/?retryWrites=true&w=majority&appName=medicineshareapp-cluster
spring.data.mongodb.database=medshare_db
spring.data.mongodb.auto-index-creation=true
